### ISSUE TITLE
Use of 'Categorical' for a type of measurement

### ISSUE THREAD

**Issue by phismith** [Planteome/variable-issue-submission#14]
## Submitter

|             |                     |
| ----------- | ------------------- |
| **Name**    | Barry Smith    |
| **Program** | Crop Ontology |

## Request

I notice that one of the entries under
'Measurement'
is labeled 'Categorical' 
Normally for what I think is meant here in connection with measurement one uses 'qualitative' (as contrasted with 'numerical') 
'Categorical' means something quite different

|                        |                           |
| ---------------------- | ------------------------- |
| **Trait Name**         | {{data["trait-name"]}}    |
| **Definition**         | {{data["trait-def"]}}     |
| **Trait Class**        | {{data["trait-class"]}}   |
| **Measurement Method** | {{data["method"]}}        |
| **Measurement Type**   | {{data["variable-type"]}} |
{% if data["variable-type"]=="Unit" %}
| **Measurement Unit**   | {{data["unit"]}}           |
{% else %}

#### Categories

| ID       | Description |
| -------- | ----------- |
{% for c in data["categories"] %}
| **{{c[0]}}** | {{c[1]}}    |
{% endfor %}
{% endif %}

**Comment by marieALaporte** [comment]
Breeder are used to hear the term 'categorical' for their scales of measurement.
In the submission form, we reused the terminology of the Trait Dictionary that we have at Crop Ontology.
More information about our TD can be found here: http://www.cropontology.org/CropOntology_Curation_Guidelines_20160510.pdf
The form does not intend to be semantically correct but is just an interface to communicate with the breeders.
If you think that categorical is misleading, we can change it to qualitative.
@elizabetharnaud  @nmenda what do you think?

**Comment by dauglyon** [comment]
Really the categorical option encompass not only nominal but also dichotomous and ordinal values. A qualitative/quantitative option would definitely be more semantically correct in my opinion, but I don't know about the communication angle.

**Comment by nmenda** [comment]
I think we should use the terminology that breeders use, so whatever makes sense to the users is language that needs to be used in the form

**Comment by phismith** [comment]
I certainly think a change to 'qualitative' would be advisable
BS

**Comment by phismith** [comment]
The more successful an ontology becomes, the more it will be used by wider
communities (who will likely associate quite different meanings with
'categorical')
BS

**Comment by dauglyon** [comment]
Whats the consensus on this?
