### ISSUE TITLE
'Add Category' button looks squished on my browser

### ISSUE THREAD

**Issue by cooperl09** [Planteome/variable-issue-submission#16]
You might need to adjust the size of the button, or make it auto scale.  It is difficult to read.

I am using Firefox 56.0.2 (64-bit)

**Comment by dauglyon** [comment]
How does it look now? (you might need to do a <kbd>cmd / ctrl</kbd> + <kbd>shift</kbd> + <kbd>r</kbd> refresh)

**Comment by dauglyon** [comment]
It was just a weird CSS artifact fixed with: 1ce0a98

**Comment by cooperl09** [comment]
Looks better to me, thanks for quick resolution
