### ISSUE TITLE
fresh root weight

### ISSUE THREAD

**Issue by rtbbase-helper** [Planteome/variable-issue-submission#21]
## Submitter

|             |                     |
| ----------- | ------------------- |
| **Name**    | guillaune bauchet    |
| **Program** | BTI |

## Request

|                        |                           |
| ---------------------- | ------------------------- |
| **Trait Name**         | fresh root weight    |
| **Definition**         | fresh weight of total cassava roots at harvest  at plot level     |
| **Trait Class**        | Agronomic   |
| **Measurement Method** | weighing         |
| **Measurement Type**   | Unit |
| **Measurement Unit**   | kilograms           |

**Comment by dcornet** [comment]
Are you collecting all roots or only commercial roots
